"""add_byok_and_api_keys

Revision ID: 25ac817a176b
Revises: 796761939f88
Create Date: 2026-01-11 12:55:36.130521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ac817a176b'
down_revision: Union[str, Sequence[str], None] = '796761939f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_budgets', sa.Column('openai_api_key', sa.String(length=255), nullable=True))
    op.add_column('llm_budgets', sa.Column('claude_api_key', sa.String(length=255), nullable=True))
    op.add_column('llm_budgets', sa.Column('google_api_key', sa.String(length=255), nullable=True))
    op.add_column('llm_budgets', sa.Column('groq_api_key', sa.String(length=255), nullable=True))
    op.add_column('llm_usage', sa.Column('is_byok', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_usage', 'is_byok')
    op.drop_column('llm_budgets', 'groq_api_key')
    op.drop_column('llm_budgets', 'google_api_key')
    op.drop_column('llm_budgets', 'claude_api_key')
    op.drop_column('llm_budgets', 'openai_api_key')
    # ### end Alembic commands ###
