"""add_llm_budgets_table

Revision ID: 58130c25a4ca
Revises: 9ec1f3bc2370
Create Date: 2026-01-09 05:18:12.796527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58130c25a4ca'
down_revision: Union[str, Sequence[str], None] = '9ec1f3bc2370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('monthly_limit_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('alert_threshold_percent', sa.Integer(), nullable=False),
    sa.Column('hard_limit', sa.String(length=10), nullable=False),
    sa.Column('alert_sent_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_llm_budgets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_budgets'))
    )
    op.create_index(op.f('ix_llm_budgets_tenant_id'), 'llm_budgets', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_budgets_tenant_id'), table_name='llm_budgets')
    op.drop_table('llm_budgets')
    # ### end Alembic commands ###
