"""Add LLM usage table

Revision ID: 6e0db32e8ee9
Revises: 3203ef5d002a
Create Date: 2026-01-08 20:06:20.133969

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6e0db32e8ee9'
down_revision: Union[str, Sequence[str], None] = '3203ef5d002a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
