"""add_trial_started_at_to_tenants

Revision ID: af06395c042b
Revises: e3f4a5b6c7d8
Create Date: 2026-01-14 00:11:54.610139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af06395c042b'
down_revision: Union[str, Sequence[str], None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_subscriptions_paystack_customer_code'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_tenant_id'), table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_constraint(op.f('fk_carbon_settings_tenant_id_tenants'), 'carbon_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_carbon_settings_tenant_id_tenants'), 'carbon_settings', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('llm_budgets', 'openai_api_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('llm_budgets', 'claude_api_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('llm_budgets', 'google_api_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('llm_budgets', 'groq_api_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.add_column('tenants', sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'trial_started_at')
    op.alter_column('llm_budgets', 'groq_api_key',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('llm_budgets', 'google_api_key',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('llm_budgets', 'claude_api_key',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('llm_budgets', 'openai_api_key',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_carbon_settings_tenant_id_tenants'), 'carbon_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_carbon_settings_tenant_id_tenants'), 'carbon_settings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table('tenant_subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('paystack_customer_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('paystack_subscription_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tier', sa.VARCHAR(length=20), server_default=sa.text("'free'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('current_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('canceled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('paystack_email_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('next_payment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_subscriptions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_subscriptions')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_subscriptions_tenant_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tenant_subscriptions_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_paystack_customer_code'), 'tenant_subscriptions', ['paystack_customer_code'], unique=False)
    # ### end Alembic commands ###
