"""Add explainable ActiveOps support

Revision ID: bc211fc9da0a
Revises: 25ac817a176b
Create Date: 2026-01-11 15:13:40.081901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc211fc9da0a'
down_revision: Union[str, Sequence[str], None] = '25ac817a176b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediation_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('auto_pilot_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_confidence_threshold', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_remediation_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediation_settings')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_remediation_settings_tenant_id'))
    )
    op.alter_column('aws_connections', 'role_arn',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.alter_column('aws_connections', 'region',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'us-east-1'::character varying"))
    op.alter_column('aws_connections', 'last_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_aws_connections_aws_account_id'), table_name='aws_connections')
    op.alter_column('carbon_settings', 'carbon_budget_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('100.0'))
    op.alter_column('carbon_settings', 'alert_threshold_percent',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('80'))
    op.alter_column('carbon_settings', 'default_region',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'us-east-1'::character varying"))
    op.alter_column('carbon_settings', 'email_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('carbon_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carbon_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('carbon_settings_tenant_id_key'), 'carbon_settings', type_='unique')
    op.create_unique_constraint(op.f('uq_carbon_settings_tenant_id'), 'carbon_settings', ['tenant_id'])
    op.drop_constraint(op.f('carbon_settings_tenant_id_fkey'), 'carbon_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_carbon_settings_tenant_id_tenants'), 'carbon_settings', 'tenants', ['tenant_id'], ['id'])
    op.add_column('llm_budgets', sa.Column('openai_api_key', sa.String(length=512), nullable=True))
    op.add_column('llm_budgets', sa.Column('claude_api_key', sa.String(length=512), nullable=True))
    op.add_column('llm_budgets', sa.Column('google_api_key', sa.String(length=512), nullable=True))
    op.add_column('llm_budgets', sa.Column('groq_api_key', sa.String(length=512), nullable=True))
    op.alter_column('llm_budgets', 'hard_limit',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=False,
               postgresql_using="hard_limit::boolean")
    op.alter_column('llm_budgets', 'alert_sent_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="alert_sent_at::timestamp with time zone")
    op.add_column('llm_usage', sa.Column('is_byok', sa.Boolean(), nullable=True))
    op.execute("UPDATE llm_usage SET is_byok = false")
    op.alter_column('llm_usage', 'is_byok', nullable=False)
    op.drop_index(op.f('ix_notification_settings_tenant_id'), table_name='notification_settings')
    op.add_column('remediation_requests', sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('remediation_requests', sa.Column('explainability_notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remediation_requests', 'explainability_notes')
    op.drop_column('remediation_requests', 'confidence_score')
    op.create_index(op.f('ix_notification_settings_tenant_id'), 'notification_settings', ['tenant_id'], unique=False)
    op.drop_column('llm_usage', 'is_byok')
    op.alter_column('llm_budgets', 'alert_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('llm_budgets', 'hard_limit',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('llm_budgets', 'groq_api_key')
    op.drop_column('llm_budgets', 'google_api_key')
    op.drop_column('llm_budgets', 'claude_api_key')
    op.drop_column('llm_budgets', 'openai_api_key')
    op.drop_constraint(op.f('fk_carbon_settings_tenant_id_tenants'), 'carbon_settings', type_='foreignkey')
    op.create_foreign_key(op.f('carbon_settings_tenant_id_fkey'), 'carbon_settings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_carbon_settings_tenant_id'), 'carbon_settings', type_='unique')
    op.create_unique_constraint(op.f('carbon_settings_tenant_id_key'), 'carbon_settings', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('carbon_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carbon_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carbon_settings', 'email_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('carbon_settings', 'default_region',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'us-east-1'::character varying"))
    op.alter_column('carbon_settings', 'alert_threshold_percent',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('80'))
    op.alter_column('carbon_settings', 'carbon_budget_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('100.0'))
    op.create_index(op.f('ix_aws_connections_aws_account_id'), 'aws_connections', ['aws_account_id'], unique=False)
    op.alter_column('aws_connections', 'last_verified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('aws_connections', 'region',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'us-east-1'::character varying"))
    op.alter_column('aws_connections', 'role_arn',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_table('remediation_settings')
    # ### end Alembic commands ###
