"""restore_multicloud_and_add_gcp_fields

Revision ID: c5127e32a8b0
Revises: bb772b6f1c3b
Create Date: 2026-01-16 09:39:02.406818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'c5127e32a8b0'
down_revision: Union[str, Sequence[str], None] = 'bb772b6f1c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azure_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('azure_tenant_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('client_secret', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('auth_method', sa.String(), server_default='secret', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_azure_connections_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_azure_connections'))
    )
    op.create_index(op.f('ix_azure_connections_tenant_id'), 'azure_connections', ['tenant_id'], unique=False)
    op.create_table('gcp_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('service_account_json', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('auth_method', sa.String(), server_default='secret', nullable=False),
    sa.Column('billing_project_id', sa.String(), nullable=True),
    sa.Column('billing_dataset', sa.String(), nullable=True),
    sa.Column('billing_table', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_gcp_connections_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gcp_connections'))
    )
    op.create_index(op.f('ix_gcp_connections_tenant_id'), 'gcp_connections', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gcp_connections_tenant_id'), table_name='gcp_connections')
    op.drop_table('gcp_connections')
    op.drop_index(op.f('ix_azure_connections_tenant_id'), table_name='azure_connections')
    op.drop_table('azure_connections')
    # ### end Alembic commands ###
