"""
AWS Connection Model

Stores AWS cross-account role connections for multi-tenant cost analysis.

Security:
- Uses IAM AssumeRole (no long-lived credentials stored)
- External ID prevents confused deputy attacks
- Credentials are temporary (1 hour max)

Usage:
    connection = AWSConnection(
        tenant_id=tenant.id,
        aws_account_id="123456789012",
        role_arn="arn:aws:iam::123456789012:role/ValdrixReadOnly",
        external_id="cs-abc123-xyz789",
        region="us-east-1"
    )
"""

import uuid
import secrets
from sqlalchemy import Column, String, ForeignKey, DateTime, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.base import Base


from sqlalchemy_utils import StringEncryptedType
from sqlalchemy_utils.types.encrypted.encrypted_type import AesEngine
from app.core.config import get_settings

settings = get_settings()
# If ENCRYPTION_KEY is missing, use fallback for dev, but this should be set in prod
# The key for AesEngine must be 16, 24, or 32 bytes (128, 192, or 256 bits)
_encryption_key = settings.ENCRYPTION_KEY or "dev-unsecure-key-16bytes!!"

class AWSConnection(Base):
    """
    Represents a user's AWS account connection to Valdrix.
    
    Flow:
    1. User deploys CloudFormation to create IAM role in their account
    2. User registers the role ARN here
    3. Valdrix uses STS AssumeRole to get temp credentials
    4. Scheduler uses temp credentials to fetch cost data
    """
    
    __tablename__ = "aws_connections"
    
    # Primary key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    # Foreign key: Which tenant owns this connection
    tenant_id = Column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    # AWS Account Details
    # aws_account_id: 12-digit AWS account number
    aws_account_id = Column(String(12), nullable=False)
    
    # role_arn: Full ARN of the IAM role to assume
    # Format: arn:aws:iam::123456789012:role/ValdrixReadOnly
    # ENCRYPTED at rest
    role_arn = Column(
        StringEncryptedType(String(2048), _encryption_key, AesEngine, "pkcs5"), 
        nullable=False
    )
    
    # external_id: Unique identifier for confused deputy prevention
    # Generated by Valdrix, user must add to role trust policy
    # ENCRYPTED at rest
    external_id = Column(
        StringEncryptedType(String(64), _encryption_key, AesEngine, "pkcs5"), 
        nullable=False, 
        default=lambda: f"cs-{secrets.token_hex(16)}"
    )
    
    # region: Default AWS region for Cost Explorer queries
    region = Column(String(20), nullable=False, default="us-east-1")
    
    # Connection Status
    # pending: User registered but not verified
    # active: Connection verified and working
    # error: Last verification failed
    status = Column(String(20), nullable=False, default="pending")
    
    # Timestamps for tracking
    last_verified_at = Column(DateTime, nullable=True)
    
    # Error message if status is "error"
    error_message = Column(Text, nullable=True)
    
    # created_at and updated_at inherited from Base
    
    # Relationship to tenant
    tenant = relationship("Tenant", back_populates="aws_connections")
    
    def __repr__(self):
        return f"<AWSConnection {self.aws_account_id} ({self.status})>"
    
    @classmethod
    def generate_external_id(cls) -> str:
        """Generate a unique external ID for a new connection."""
        return f"cs-{secrets.token_hex(16)}"
