"""
AWS Connection Model

Stores AWS cross-account role connections for multi-tenant cost analysis.

Security:
- Uses IAM AssumeRole (no long-lived credentials stored)
- External ID prevents confused deputy attacks
- Credentials are temporary (1 hour max)

Usage:
    connection = AWSConnection(
        tenant_id=tenant.id,
        aws_account_id="123456789012",
        role_arn="arn:aws:iam::123456789012:role/ValdrixReadOnly",
        external_id="vx-abc123-xyz789",
        region="us-east-1"
    )
"""

from uuid import UUID, uuid4
import secrets
from datetime import datetime
from sqlalchemy import String, ForeignKey, DateTime, Text, Boolean, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import relationship, Mapped, mapped_column

from app.shared.db.base import Base


from sqlalchemy_utils import StringEncryptedType
from sqlalchemy_utils.types.encrypted.encrypted_type import AesEngine
from app.shared.core.config import get_settings

settings = get_settings()
_encryption_key = settings.ENCRYPTION_KEY

class AWSConnection(Base):
    """
    Represents a user's AWS account connection to Valdrix.

    Flow:
    1. User deploys CloudFormation to create IAM role in their account
    2. User registers the role ARN here
    3. Valdrix uses STS AssumeRole to get temp credentials
    4. Scheduler uses temp credentials to fetch cost data
    """

    __tablename__ = "aws_connections"
    __table_args__ = (
        UniqueConstraint('tenant_id', 'aws_account_id', name='uq_tenant_aws_account'),
    )

    # Primary key
    id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid4)

    # Foreign key: Which tenant owns this connection
    tenant_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # AWS Account Details
    # aws_account_id: 12-digit AWS account number
    aws_account_id: Mapped[str] = mapped_column(String(12), nullable=False)

    # role_arn: Full ARN of the IAM role to assume
    # Format: arn:aws:iam::123456789012:role/ValdrixReadOnly
    # ENCRYPTED at rest
    role_arn: Mapped[str] = mapped_column(
        StringEncryptedType(String(2048), _encryption_key, AesEngine, "pkcs5"),
        nullable=False
    )

    # external_id: Unique identifier for confused deputy prevention
    # Generated by Valdrix, user must add to role trust policy
    # ENCRYPTED at rest
    external_id: Mapped[str] = mapped_column(
        StringEncryptedType(String(64), _encryption_key, AesEngine, "pkcs5"),
        nullable=False,
        default=lambda: f"vx-{secrets.token_hex(16)}"
    )

    # region: Default AWS region for Cost Explorer queries
    region: Mapped[str] = mapped_column(String(20), nullable=False, default="us-east-1")

    # Connection Status
    # pending: User registered but not verified
    # active: Connection verified and working
    # error: Last verification failed
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    
    # AWS Organizations Support
    is_management_account: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")
    organization_id: Mapped[str | None] = mapped_column(String(32), nullable=True)

    # Timestamps for tracking
    last_verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Error message if status is "error"
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    # CUR (Cost and Usage Report) Automation
    # none, setting_up, active, error
    cur_status: Mapped[str] = mapped_column(String(20), nullable=False, default="none")
    cur_bucket_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    cur_report_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    
    # Health Tracking
    # Updated by JobProcessor when costs are successfully ingested
    last_ingested_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # created_at and updated_at inherited from Base

    # Relationship to tenant
    tenant: Mapped["Tenant"] = relationship("Tenant", back_populates="aws_connections")

    @property
    def provider(self) -> str:
        return "aws"

    def __repr__(self):
        return f"<AWSConnection {self.aws_account_id} ({self.status})>"

    @classmethod
    def generate_external_id(cls) -> str:
        """Generate a unique external ID for a new connection."""
        return f"vx-{secrets.token_hex(16)}"
